### ISSUE TITLE
Path to component is shown in the resource form

### ISSUE THREAD

**Issue by sonicpunk** [Jako/ColorPicker#1]
MODX Revo 2.5.7
ColorPicker 1.0.3

In the MODX interface an assets link is shown.

![screen-shot-2017-12-08-at-11 50 38-x](https://user-images.githubusercontent.com/447453/33762853-7e5fcfb0-dc0e-11e7-95fe-3ec4b54ebcd6.jpg)
![screen-shot-2017-12-08-at-11 50 50-x](https://user-images.githubusercontent.com/447453/33762854-7e7b89da-dc0e-11e7-85f2-39f668524d10.jpg)

**Comment by sonicpunk** [comment]
When display errors is active and error setting is set to 'all' in MODX settings, this path gets shown.

**Comment by Jako** [comment]
Thats not an issue in ColorPicker. Image+ shows the same error in some conditions: https://github.com/Jako/ImagePlus/issues/22#issuecomment-249375385
