### ISSUE TITLE
Existing TV values altered and color map not working

### ISSUE THREAD

**Issue by SnowCreative** [Jako/ColorPicker#4]
I installed this today, and ALL of my TVs got a hash mark inserted at the front, when there was none before! This broke all my existing scripts/chunks. Also, the popup displays only a single color, not a color map:
![Screen Shot 2022-02-09 at 3 35 15 PM](https://user-images.githubusercontent.com/2528374/153285506-d8e38e0f-89e7-4c21-81c0-0f4a9fde03a4.png)

MODX 2.8.3 / Colorpicker 2.0.0

**Comment by Jako** [comment]
The hash change is documented in the changelog in the first place. How can I make it more prominent? The popup looks like the old version, maybe you have to do a force reload, but this is strange.

**Comment by SnowCreative** [comment]
Yes, that's the old popup, but it broke when I installed the new plugin, and the color map didn't fix itself when I reverted to the previous version.

I don't understand why this change was made. Everyone who has scripts and chunks manually adding the hash marks where needed now has to track down every instance and manually change them. I have one site that has literally hundreds of TV values using this plugin, and many many chunks, templates, and scripts processing the TV values.

I really like the new features, but the hash mark change makes it a deal-breaker for my sites that have a lot of Colorpicker TV values and scripting. Maybe there should be a system setting to enable or disable the hashmark in saved values? And/or maybe an option during the upgrade installation to add hashes or not?

I have over 100 sites, and I update them all at once using SiteDash, so I didn't see this coming at all.

**Comment by SnowCreative** [comment]
In another site with this updated plugin, the TV input looks like this:
![Screen Shot 2022-02-09 at 4 24 48 PM](https://user-images.githubusercontent.com/2528374/153292655-add193e9-968b-4f22-941d-aa64cebb0ec0.png)

I deleted the entire cache folder, and cleared the browser cache, and nothing changes. I had to re-edit each Colorpicker TV and resave it to make it work properly.

**Comment by Jako** [comment]
I am very sorry that you are having issues with the new version of ColorPicker.

The new colorpicker needs this change. It will be a lot of work and maybe impossible to remove the hash before the value is saved. What can be prepared is to create an output option without the hash.

It is a breaking change. So I created a new major version and put the info about this change in the changelog. How can I make this more prominent?

I can investigate the issue, that happens on the second site. Can you post the database entry of the tv itself before the update here?

**Comment by Jako** [comment]
Please reinstall the old version of the TV on the first site (this will install the colormap image) and remove the prepending hash from all values in site_tmplvar_contentvalues for ColorPicker TVs.

The opposite way is done in https://github.com/Jako/ColorPicker/blob/master/_build/resolvers/resolve.version.php

**Comment by SnowCreative** [comment]
Here are screen shots of the previous version of the TV from VersionX. Is this what you need?

![Screen Shot 2022-02-09 at 5 09 53 PM](https://user-images.githubusercontent.com/2528374/153298705-c8bcb6f7-0b27-48f7-88b3-dd1cb9214b78.png)

![Screen Shot 2022-02-09 at 5 09 58 PM](https://user-images.githubusercontent.com/2528374/153298724-97c08e47-3a4b-44da-bb0a-58b73b9a4412.png)

![Screen Shot 2022-02-09 at 5 10 01 PM](https://user-images.githubusercontent.com/2528374/153298741-4d3a21c7-34c4-4029-9e13-bf227433f286.png)

![Screen Shot 2022-02-09 at 5 10 07 PM](https://user-images.githubusercontent.com/2528374/153298756-69fde941-dcfc-4e07-a0a9-d8b04b675554.png)

**Comment by SnowCreative** [comment]
> It is a breaking change. So I created a new major version and put the info about this change in the changelog. How can I make this more prominent?

I guess I should make it a habit to check changelogs for plugins before I use SiteDash to update all sites, especially if it's a major version update! I always just assume everything will be fine. 🙂

**Comment by SnowCreative** [comment]
> Please reinstall the old version of the TV on the first site (this will install the colormap image) and remove the prepending hash from all values in site_tmplvar_contentvalues for ColorPicker TVs.

Yes, that's what I did already. Now, I have to go into the 19 other sites that use the plugin to evaluate what to do 😢. Some will be easy to make work with the new plugin. I _**DO**_ really like it!

**Comment by Jako** [comment]
Thanks for the screenshots. To understand the issue right: The TV value on the page where the new colorpicker is shown was empty or was it filled before the update?

**Comment by SnowCreative** [comment]
It was empty.

**Comment by Jako** [comment]
Then you see just the new colorpicker …

**Comment by Jako** [comment]
I can add a new version with an output option that removes the hash tomorrow if that helps.

**Comment by SnowCreative** [comment]
>Then you see just the new colorpicker …

Yes, but it doesn't work. No color code gets selected or inserted when I click on a color in the color map.

>I can add a new version with an output option that removes the hash tomorrow if that helps.

That's a great idea.

**Comment by Jako** [comment]
Or you patch that change into the output code here: https://github.com/Jako/ColorPicker/blob/master/core/components/colorpicker/elements/tv/output/colorpicker.class.php#L61

```
return ($output) ? substr($output, 1) : '';
```

**Comment by SnowCreative** [comment]
FYI, speaking of output options, when I edit a TV in a site I just updated, the Output options has two popups, and the second has no label and nothing in it:
![Screen Shot 2022-02-09 at 5 34 42 PM](https://user-images.githubusercontent.com/2528374/153301962-78ad7fcb-fc79-48c6-819c-a26e8154e2e5.png)

The first one has the name "prop_color_format" and the second one is "prop_color_output".

**Comment by SnowCreative** [comment]
> Or you patch that change into the output code here:

Yes, but I'd rather not monkey with your code, since it will get replaced on the next update anyway!

**Comment by Jako** [comment]
There should be 3 columns. Can you post the value of the output_properties column in modx_site_tmplvars of that TV?

![Bildschirmfoto 2022-02-09 um 23 41 04](https://user-images.githubusercontent.com/148371/153302667-80e541a4-dde7-43a8-8057-ccdd9548f3d5.png)

**Comment by Jako** [comment]
I will answer tomorrow morning next. I have to sleep now.

**Comment by SnowCreative** [comment]
>There should be 3 columns. Can you post the value of the output_properties column in modx_site_tmplvars of that TV?

It's NULL. Two other TVs have the same to popups, and they have "a:0:{}" for output_properties. If I change the input settings, save the TV, then change them back and save again, then output_properties gets filled in, but the same two popups appear, with the second one empty. The output_properties then shows this:

a:2:{s:12:"color_format";s:3:"hex";s:12:"color_output";s:3:"css";}

Completely deleting the cache folder and browser cache doesn't change anything.

Next I tried reinstalling the update, and the update process froze after:

Attempting to preserve files at [CORE PATH]/components/colorpicker into archive [CORE PATH]/packages/colorpicker-2.0.0-pl/modCategory/b171f394d477cb2ae0ae4476e81e538d.1.preserved.zip

I tried reverting, deleting the update package, redownloading it, and reinstalling, and it still hangs up during installation and won't complete. I updated PHP from 7.2 to 7.3, and that didn't change anything.

On a different site, there is no problem, and the output settings look just like your screen shot. Kind of baffling.

**Comment by Jako** [comment]
MODX loads the content there on base of the content of the files in `core/components/colorpicker/elements/tv/output`. Maybe the files are not changed inside because of file writing issues.

**Comment by Jako** [comment]
2.0.1 is avaliable, allowing stripping the # from the output.

**Comment by Jako** [comment]
Is your problem solved with this? Unfortunately, the database value must be changed.

**Comment by SnowCreative** [comment]
I'm having a lot of trouble getting this installed, so I can't test. I've tried on several sites, and only one updated properly. On the the ones that don't work, i've completely uninstalled the plugin, removed it, checked to make sure ALL files are deleted (core->components, assets->components, and core->packages), cleared all my browser caches and cookies, deleted everything in the core->cache folder, turn off Cloudflare caches,  and after I do a fresh install of your plugin version 2.0.1, the old version TV popups still show up instead of the new ones (or a broken composite), and the TV colorpicker Output tab only has the two stacked popup options, like I showed above. None of the old javascript should exist anywhere, and yet it does.

**Comment by Jako** [comment]
That is strange. Is some PHP optimizer running which caches/precompiles the PHP files?

**Comment by Jako** [comment]
The only thing involved there is Smarty. This uses a cache in core/cache/mgr/smarty.

**Comment by SnowCreative** [comment]
> Is some PHP optimizer running which caches/precompiles the PHP files?

Don't know, but this happens both on sites at a regular host and on sites on MODX Cloud.

**Comment by SnowCreative** [comment]
HI again. Well, the 2.0.2 update fixed a lot of the problems. On SOME sites I've updated to 2.0.2, everything works as it should.

But on other sites, the correct popup template now appears, and the right options appear when editing TVs now, but now when I try to edit a color in a resource on some sites, I get this:
![Screen Shot 2022-02-19 at 12 21 17 PM](https://user-images.githubusercontent.com/2528374/154811796-eabc6ebd-d3c2-4ed5-854a-ae33e0307d3b.png)

The color in the popup is always black, no color code shows up in the field where that should be, and there is a Delete button, which shouldn't be there. Also, on these sites, turning on "Show Alpha" in the TV settings doesn't do anything.

The following javascript error shows up in the javascript console after clicking inside a colorpicker TV field in a resource:
```
Uncaught TypeError: Cannot set properties of null (setting 'checked')
    at N (colorpicker.min.js?v=v2.0.2:6:7458)
    at A (colorpicker.min.js?v=v2.0.2:6:5226)
    at HTMLInputElement.<anonymous> (colorpicker.min.js?v=v2.0.2:6:3929)
    at HTMLDocument.<anonymous> (colorpicker.min.js?v=v2.0.2:6:11005)
```


UPDATE: If I update ALL colorpicker TVs and set the output to ColorPicker instead of Default, then editing the TV fields in resources works properly. If I then change TVs back to Default output, then they still work. So, it seems it takes manually updating all colorpicker TVs to make some settings, somewhere, update.

UPDATE 2: It seems some existing colorpicker TVs have settings in the input_properties column in the DB that don't apply, or no longer apply, and these cause the proper functioning of the editing popup to fail. For example, one color TV had this for the settings:

`a:5:{s:10:"allowBlank";s:4:"true";s:9:"maxLength";s:0:"";s:9:"minLength";s:0:"";s:5:"regex";s:0:"";s:9:"regexText";s:0:"";}
`

Updating the settings fixes the problem. Maybe create a resolver to check for invalid settings and remove them? Sorry for the trouble!

**Comment by Jako** [comment]
This is the case it was because 'format' was not set to the default value. I don't know how long your TV code did exist. It  has been used for a long time, since the old core/manager code was never updated and it did override the new tv based code. It is fixed in 2.0.2-pl2.

**Comment by Jako** [comment]
I hope that everything is fixed and close this now.

**Comment by SnowCreative** [comment]
Yes, everything good now that I know how to handle old code. Probably some of these TVs started out as text fields, and then I converted them to colorpicker fields and the input and output settings didn't get updated properly.
