### ISSUE TITLE
Colorpicker on Migx - zindex problem

### ISSUE THREAD

**Issue by JANogueira** [Jako/ColorPicker#5]
Hi @Jako,

I am migrating from the old colorpicker v1x to the new v2, and found that the new v2 has a zindex problem when used with Migx.
An example:
![image](https://user-images.githubusercontent.com/22750391/156166277-ab0adab8-f830-4145-98d4-25dbdeb4d052.png)

Z-index of Migx box is 9003, while colorpicker's zindex is 1000

v1 was fine:
![image](https://user-images.githubusercontent.com/22750391/156166367-68e547d7-5fa5-438c-ae26-721e77549297.png)

zindex of the older colorpicker was 15000 apparently.

Do you think this can be changed to 15000 to work on all use cases?
Thanks in advance.

**Comment by JANogueira** [comment]
Created a Pull Request to help with this change:
https://github.com/Jako/ColorPicker/pull/6

Hope it helps

**Comment by Jako** [comment]
Did you found a different solution?

**Comment by JANogueira** [comment]
No, just issued the Pull Request.
