### ISSUE TITLE
Display of Alpha in popup not working properly

### ISSUE THREAD

**Issue by SnowCreative** [Jako/ColorPicker#7]
When assigning several colorpicker TVs to a template, some of which have Alpha enabled and some don't, the individual Alpha options don't work. ALL of the colorpickers for the template will have the same alpha setting: the one the last TV displayed has. 

So, if I have color1 with alpha, color2 without alpha, and color3 without alpha, then when editing a resource with those three colors assigned, color1 will not have alpha enabled in the picker popup. Conversely, if I have color1 without alpha, color2 without alpha, and color3 WITH alpha, then when editing the resource, all three colors will have alpha enabled in the picker popup.

Using ColorPicker 2.0.4-pl with MODX 2.8.4

**Comment by Jako** [comment]
Fixed with 2.0.5

**Comment by SnowCreative** [comment]
Wow, what a turnaround! Works great now.
