### ISSUE TITLE
Have the value with or without '#' in the database by system setting possible?

### ISSUE THREAD

**Issue by Bruno17** [Jako/ColorPicker#8]
I'm using ColorPicker within an MIGXdb Extra.
Now I've upgraded from an older Version.
All the old values were stored without a prefix.
The new version seems to need the value prefixed with '#'.

Would it be possible to change that behaviour with a system setting,
so I can just use the old values like before without changing all my code and all values on all installations in the db?

**Comment by Bruno17** [comment]
For my usecase, I could fix it with two MIGXdb hooksnippets (aftersave and aftergetfields), where I remove the '#' aftersave and get it back into the value before editing with aftergetfields.

**Comment by Jako** [comment]
I would have suggested a plugin in OnDocFormSave to solve that. But that does not work inside of MIGXdb.

There are some reasons for the change:
- ColorPicker supports now multiple color formats
- The Javascript of mdbassit/Coloris has to be filled with a # prefix when a hex value is used.

The Prefix can be removed with the TV output options.

The change of this option is well documented in the changelog: https://github.com/Jako/ColorPicker/blob/master/core/components/colorpicker/docs/changelog.md#200---2022-02-05

**Comment by Bruno17** [comment]
Thanks Jako! 
Yeah, I understood that.
For my usecase, it was the easiest option to leave all db-entries without the # and just add it for editing and remove it again on saving.
Thanks for maintaining all that Extras!
